version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    networks:
      - backend

  db:
    container_name: db
    image: mysql:latest
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "0.0.0.0:32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend
networks:
  backend:
